### ISSUE TITLE
Option to Enable or Disable Trailing or Leading Comments

### ISSUE THREAD

**Issue by heinrich10** [eslint/espree#226]
I am experiencing duplicate comments when transforming ast to code.

I want to propose a way to enable or disable trailing and leading comments.
Rather than doing `attachComment: true`, maybe we can do something like

```javascript
{
    attachComment: {
        leading: true,
        trailing: false
    }
}
```

but the old way of attaching comment should still be supported so as not to break things. If you do

```javascript
{
    attachComment: true
}
```
then it will still attach leading and trailing comments.

this is espree 2.2.5, by the way.

Here are some issues I found related to this that might also help other users if implemented

https://github.com/eslint/espree/issues/184
https://github.com/estools/escodegen/issues/152

**Comment by nzakas** [comment]
I don't see how such a change would be helpful. Having duplicate comments is a known issue because we can't tell if a comment is leading or trailing. If you only enable one, then you will end up missing comments.

**Comment by heinrich10** [comment]
Thank you @nzakas for answering my question. 

It would be helpful if you want to convert the AST back to code again.

In my case, I parse the code and then manipulate the AST to add or remove some block of code. And then change it back into code again using escodegen. Comments are duplicated on the regenerated code because of the trailing and leading comments.

The current workaround I am doing is to traverse the whole AST and delete every single trailing comment which would waste some resources since it is being added by the library and then being deleted by my program. It would be helpful if we can have this feature.

About missing some comments, I think it would depend on the user. The user would have the option to enable trailing only, enable leading only, or enable both which makes the library a little bit more flexible.

**Comment by nzakas** [comment]
That sounds like a bug in escodegen to me. I'd suggest opening an issue there.

**Comment by heinrich10** [comment]
Not really, because they use the AST fed to it and convert it to code as is. So the root cause would be the generation of the AST. 

I tried to comment out some code in your library and it seems working. 

Just want to formalize things and see if this feature is aligned with your roadmap.

**Comment by nzakas** [comment]
I think it's a bug in escodegen because it doesn't make sense to serialize the same comments twice. Espree's behavior is identical to Esprima, so there's a decent amount of history for this approach. 

In any event, I don't see this as a good enhancement for Espree.

**Comment by ogorbacheva** [comment]
There is still a problem with duplicate comments.

**Comment by platinumazure** [comment]
@kaicataldo We (you) created a new comment attachment strategy in ESLint some time ago. Were any corresponding changes made to espree that would fix the issue described here?

**Comment by kaicataldo** [comment]
@platinumazure No changes were made to Espree. We just don't use the comment attachment option when parsing.

As @nzakas has said, this isn't a bug, but a feature request. When Espree parses, there is no way to know whether a comment is a trailing comment for the previous token or a leading comment for the next token. Given a node, you should be able to check if it has a comment before it or after it. It's up to the consumer to decide what they do with this information.

It feels to me like thinking of these as duplicated comments is wrong. The intended use case here is to be able to easily access comments around nodes. Attached comments are not nodes in the tree (this wouldn't make sense) - they are just references to the comment tokens that exist in the comments array.

I don't think adding an option to only include leading or trailing comments makes sense either, because some comments would be missed (at the beginning or end of the file, for instance).

As @nzakas mentioned, it's on the consumer to use this information correctly. My naive take is that it would either involve using attached comments and deduping them or using the comments array generated by Espree using the `comment: true` option and inserting comments in the correct place (this is more work, but I think it would be more accurate).

For reference, Babel does the first of the two options above. Babylon has a very similar comment attachment strategy and Babel does the work to dedupe comments when it generates code: https://github.com/babel/babel/blob/master/packages/babel-generator/src/printer.js#L528
