### ISSUE TITLE
Add node type for comments

### ISSUE THREAD

**Issue by FrozenKoi** [eslint/espree#336]
I've been using espree with estree-walker (https://github.com/Rich-Harris/estree-walker) and when I'm trying to check what kind of node I'm visiting, I realize that I can know if a node is of 'type' Node for most of them.

In particular I'm using this:

    typeof node === "object" && Object.getPrototypeOf(node).constructor.name === "Node"

in order to filter out the integers in the `range` subobjects. (when debugging in Visual Studio Code the variables info shows Node, for example)

When it comes to nodes representing comments, they show up as Object. Would it be possible to provide an indication that they are comments? (this is my feature request)

I see from the source code that the nodes are created by acorn, and comments are created in espree.js by the `convertAcornCommentToEsprimaComment` function.

Is relying on nodes being of certain types ok? or is their prototype an implementation detail that I should not rely on?

Would it be enough to check for the `type` property for `Line` and `Block` values (and additionally check if the node is part of the `comments`, `trailingComments` or `leadingComments` property)?

P.S. I wasn't able to add the `question` or `enhancement` labels

**Comment by kaicataldo** [comment]
Apologies for the late response!

ESLint has moved away from the using the comment attachment behavior in Espree and is now using the top level `comments` array to calculate comment attachment on the fly in ESLint core.

Technically, comments are not nodes since they have no syntactic meaning. They can also occur anywhere, which leads to the comment attachment strategy implemented (and now unused) in Espree yielding some very strange results. 

The way ESLint used to emit events for visiting comments can be seen here: https://github.com/eslint/eslint/commit/867dd2eab85b1a72e3e3492a142c9b49ad810b81#diff-0d8fb51478862f57181a128257175298. However, now that ESLint is not relying on the comment attachment behavior in Espree, I'm not sure what kind of maintenance we'll be able to do on that feature.

In my personal experience, treating comments as nodes and visiting them in the context of the AST doesn't make a lot of sense. I'm of the mind that they're much easier to reason about in the context of token lists.

Hopefully this is helpful!

**Comment by not-an-aardvark** [comment]
Closing because I don't think we're going to treat comments as nodes (explanation in https://github.com/eslint/espree/issues/336#issuecomment-309318261)
