### ISSUE TITLE
BigInt syntax

### ISSUE THREAD

**Issue by silverwind** [eslint/espree#385]
[BigInt](https://github.com/tc39/proposal-bigint), which is available in Node.js 10.4.0 and Chrome 67  introduces new syntax `1n` for numbers, I think it's time to support it.

**Comment by platinumazure** [comment]
Hi @silverwind, thanks for the issue.

Espree generally does not support Stage 3 features. Once this is in Stage 4, we'll make the necessary changes (or, more likely, consume Acorn changes that handle this functionality).

**Comment by silverwind** [comment]
Okay, let's wait on Stage 4. Feel free to close.

**Comment by platinumazure** [comment]
@silverwind You should hopefully be able to use babel-eslint to use BigInt functionality in ESLint. If there are any rules that crash in ESLint and we can make a simple defensive fix, we can fix those in ESLint even though the feature is Stage 3. Otherwise, you'll need to use eslint-plugin-babel for BigInt-specific rules or rule functionality. Hope this helps!
