### ISSUE TITLE
Breaking: remove attachComment option

### ISSUE THREAD

**Issue by kaicataldo** [eslint/espree#394]
**TSC Summary:** Now that ESLint [does not use the `attachComment` option](https://github.com/eslint/eslint/pull/7516) and given its buggy nature and maintenance cost, I think we should remove the option from Espree.

**TSC Question:** This is a breaking change, however I suspect that very few other projects are using this option.

I'm more than happy to do the work if this is accepted.

**Comment by btmills** [comment]
We discussed this in today's TSC meeting and approved it with no objections. Since this doesn't affect ESLint, it doesn't need to wait for a major release of ESLint. Thanks for volunteering to do the work, @kaicataldo!

**Comment by nfroidure** [comment]
FYI I was using it for this project https://github.com/nfroidure/jsarch and faced the issue when bumping. I replaced the default parser by `@babel/parser` but I would like to know which way you recommend to parse projects for comments now ?

**Comment by platinumazure** [comment]
@nfroidure espree still parses comments- they're just stored in a comments array rather than attached directly to nodes. You can iterate through all comments pretty easily. Looking for comments "near nodes" is a bit harder, but still possible: If you are using range info on nodes (and tokens and comments), you could get all comments that start before/after the node you're looking at and see all comments that might have been attached to the node in the old comment attachment strategy.

You could also look at ESLint's token store utilities to get an idea of how ESLint manages this information internally.

**Comment by kaicataldo** [comment]
@benmosher You can still use methods on the `SourceCode` object returned by `context.getSourceCode()` to find comments based on their location relative to a given node or token (namely `getCommentsBefore(nodeOrToken)`, `getCommentsAfter(nodeOrToken)`, and `getCommentsInside(node)`). See the docs [here](https://eslint.org/docs/developer-guide/working-with-rules#contextgetsourcecode) for more details and feel free to stop by the Gitter if something isn't clear!

**Comment by aminya** [comment]
For those who need this, I have registered the latest Espree with this feature:
https://www.npmjs.com/package/espree-attachcomment

```
npm install espree-attachcomment
```
