### ISSUE TITLE
remove sourcemap url

### ISSUE THREAD

**Issue by tjx666** [eslint/espree#566]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/41773861/226166008-f3396b2c-c725-4587-af90-123e0174f090.png">

version: espree@9.5.0

**Comment by Rec0iL99** [comment]
Hi @tjx666, thanks for the issue. The `sourceMappingURL` comment is autogenerated by rollup and helps navigate to the source map file and finally to the original source code during debugging. I believe this comment is generated by rollup because of `sourcemap: true` in [`rollup.config.js`](https://github.com/eslint/espree/blob/5c85ea8a20d505342e48af456108e96edd8e20da/rollup.config.js#L12).

**Comment by tjx666** [comment]
@Rec0iL99 

You should set `sourcemap: false` when build for production, or it will cause debugger tools issue because you decale the sourceMappingURL but not actually exists;

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/41773861/226199909-09f8f56a-70dd-401e-9fef-c20bb19ffd75.png">

**Comment by aladdin-add** [comment]
instead, I think we should publish the sourcemap files, for better debugging.

**Comment by nzakas** [comment]
We don't actually need the source files for debugging as the source is in ESM already. We should just remove `sourcemap:true` from `rollup.config.js`.

**Comment by tjx666** [comment]
@nzakas https://github.com/eslint/espree/pull/567

**Comment by mdjermanovic** [comment]
@nzakas was this intentionally labeled as a breaking change?

**Comment by nzakas** [comment]
Oops! No. I meant to label as "bug". Thanks for catching that.
